name: deepvisionlecture
channels:
  - pytorch
  - conda-forge
  - defaults
  
dependencies:
  - python=3.6
  - numpy
  - scikit-learn
  - scikit-image
  - tqdm
  - pytorch
  - torchvision
  - ipykernel
  - jupyterlab

